// Generated by build_sw.py — caches the whole game so it runs offline as an installed app.
const VERSION = 'hawkvr-70cd93ea95';
const FILES = [
"./",
"./index.html",
"./manifest.webmanifest",
"./assets/character_map.json",
"./assets/characters.json",
"./assets/audio/music/forest-2.ogg",
"./assets/audio/sfx/acorn_crush.ogg",
"./assets/audio/sfx/acorn_growl.ogg",
"./assets/audio/sfx/acorn_squeak.ogg",
"./assets/audio/sfx/bat_attack.ogg",
"./assets/audio/sfx/bat_die.ogg",
"./assets/audio/sfx/boulder-crumble.ogg",
"./assets/audio/sfx/click.ogg",
"./assets/audio/sfx/confirm.ogg",
"./assets/audio/sfx/damage.ogg",
"./assets/audio/sfx/death.ogg",
"./assets/audio/sfx/hit.ogg",
"./assets/audio/sfx/jump.ogg",
"./assets/audio/sfx/meow.ogg",
"./assets/audio/sfx/pickup.ogg",
"./assets/audio/sfx/punch.ogg",
"./assets/audio/sfx/respawn.ogg",
"./assets/images/blocks/boulder-crumble.png",
"./assets/images/blocks/boulder.png",
"./assets/images/blocks/dirt-block.png",
"./assets/images/blocks/grass-block.png",
"./assets/images/characters/abed/base.png",
"./assets/images/characters/annie/base.png",
"./assets/images/characters/britta/base.png",
"./assets/images/characters/buddy/base.png",
"./assets/images/characters/chang/base.png",
"./assets/images/characters/dean/base.png",
"./assets/images/characters/duncan/base.png",
"./assets/images/characters/fatneil/base.png",
"./assets/images/characters/garrett/base.png",
"./assets/images/characters/gilbert/base.png",
"./assets/images/characters/guzman/base.png",
"./assets/images/characters/jeff/base.png",
"./assets/images/characters/leonard/base.png",
"./assets/images/characters/pierce/base.png",
"./assets/images/characters/rich/base.png",
"./assets/images/characters/shirley/base.png",
"./assets/images/characters/troy/base.png",
"./assets/images/characters/vaughn/base.png",
"./assets/images/characters/vicedean/base.png",
"./assets/images/characters/vicki/base.png",
"./assets/images/enemies/acorn.png",
"./assets/images/enemies/bat.png",
"./assets/images/enemies/cat.png",
"./assets/images/enemies/fish.png",
"./assets/images/enemies/monkey.png",
"./assets/images/liquid/water.png",
"./assets/images/liquid/waterfall.png",
"./assets/images/materials/leaf.png",
"./assets/images/materials/rock.png",
"./assets/images/materials/stick.png",
"./assets/images/tilesets/forest.png",
"./assets/levels/forest-2.json",
"./assets/levels/forest.json",
"./icons/apple-touch-icon.png",
"./icons/icon-192.png",
"./icons/icon-512.png",
"./icons/maskable-512.png",
"./js/audio.js",
"./js/collision.js",
"./js/entities.js",
"./js/env.js",
"./js/hud.js",
"./js/input.js",
"./js/level.js",
"./js/main.js",
"./js/menu.js",
"./js/mr.js",
"./js/sprite.js",
"./js/world.js",
"./vendor/three/LICENSE",
"./vendor/three/three.module.min.js",
"./vendor/three/addons/libs/motion-controllers.module.js",
"./vendor/three/addons/loaders/GLTFLoader.js",
"./vendor/three/addons/utils/BufferGeometryUtils.js",
"./vendor/three/addons/webxr/OculusHandModel.js",
"./vendor/three/addons/webxr/OculusHandPointerModel.js",
"./vendor/three/addons/webxr/VRButton.js",
"./vendor/three/addons/webxr/XRButton.js",
"./vendor/three/addons/webxr/XRControllerModelFactory.js",
"./vendor/three/addons/webxr/XRHandMeshModel.js",
"./vendor/three/addons/webxr/XRHandModelFactory.js",
"./vendor/three/addons/webxr/XRHandPrimitiveModel.js"
];

self.addEventListener('install', e => {
  e.waitUntil(caches.open(VERSION).then(c => c.addAll(FILES)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', e => {
  e.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k !== VERSION).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});
self.addEventListener('fetch', e => {
  const url = new URL(e.request.url);
  if (e.request.method !== 'GET') return;
  if (url.origin !== location.origin) {
    // Fonts / controller models: network first, fall back to cache
    e.respondWith(fetch(e.request).then(r => { const copy = r.clone(); caches.open(VERSION).then(c => c.put(e.request, copy)).catch(() => {}); return r; })
      .catch(() => caches.match(e.request)));
    return;
  }
  e.respondWith(caches.match(e.request, { ignoreSearch: true }).then(hit => hit || fetch(e.request)));
});
