#!/usr/bin/env python3
"""Write sw.js with a precache list of every file in the build, versioned by content hash."""
import hashlib, json, os, sys

ROOT = sys.argv[1]
skip = {'sw.js'}
files, h = [], hashlib.sha1()
for dp, dn, fn in os.walk(ROOT):
    dn[:] = sorted(d for d in dn if not d.startswith('.'))
    for f in sorted(fn):
        rel = os.path.relpath(os.path.join(dp, f), ROOT).replace(os.sep, '/')
        if rel in skip or f.startswith('.') or rel.endswith('.md') or rel.startswith('tools/'):
            continue
        files.append('./' + rel)
        with open(os.path.join(dp, f), 'rb') as fh:
            h.update(rel.encode()); h.update(fh.read())
version = h.hexdigest()[:10]
files.insert(0, './')

sw = f"""// Generated by build_sw.py — caches the whole game so it runs offline as an installed app.
const VERSION = 'hawkvr-{version}';
const FILES = {json.dumps(files, indent=0)};

self.addEventListener('install', e => {{
  e.waitUntil(caches.open(VERSION).then(c => c.addAll(FILES)).then(() => self.skipWaiting()));
}});
self.addEventListener('activate', e => {{
  e.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k !== VERSION).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
}});
self.addEventListener('fetch', e => {{
  const url = new URL(e.request.url);
  if (e.request.method !== 'GET') return;
  if (url.origin !== location.origin) {{
    // Fonts / controller models: network first, fall back to cache
    e.respondWith(fetch(e.request).then(r => {{ const copy = r.clone(); caches.open(VERSION).then(c => c.put(e.request, copy)).catch(() => {{}}); return r; }})
      .catch(() => caches.match(e.request)));
    return;
  }}
  e.respondWith(caches.match(e.request, {{ ignoreSearch: true }}).then(hit => hit || fetch(e.request)));
}});
"""
open(os.path.join(ROOT, 'sw.js'), 'w').write(sw)
print('sw.js', version, len(files), 'files')
